export const facilities = [
  {
    id: 1,
    name: 'Ahmed Amerovic',
    specialisation: 'pediatrician',
    languagues: 'serbian, czech',
    link: 'url',
  },
  {
    id: 2,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'russian, english',
    link: 'www.google.com',
  },
  {
    id: 3,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'german, czech',
    link: 'www.google.com',
  },
  {
    id: 4,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'russian, english, czech, arabic',
    link: 'www.google.com',
  },
  {
    id: 5,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'english, czech',
    link: 'www.google.com',
  },
  {
    id: 6,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'german, czech',
    link: 'www.google.com',
  },
  {
    id: 7,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'german, czech',
    link: 'www.google.com',
  },
  {
    id: 8,
    name: 'Doktor Mengele',
    specialisation: 'opthalmologist',
    languagues: 'german, czech',
    link: 'www.google.com',
  },
];
